# Generated by Django 2.2.4 on 2019-12-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=150)),
                ('api_key', models.CharField(max_length=150)),
                ('access_token', models.CharField(blank=True, max_length=150)),
                ('teacher', models.ForeignKey(on_delete='CASCADE', to='teacher.Teacher')),
            ],
        ),
    ]
